---
xbps_repository_main: https://alpha.de.repo.voidlinux.org/current
xbps_repository_nonfree: https://alpha.de.repo.voidlinux.org/current/nonfree
xbps_repository_multilib: https://alpha.de.repo.voidlinux.org/current/multilib
xbps_repository_multilib_nonfree: https://alpha.de.repo.voidlinux.org/current/multilib/nonfree
xbps_repository_address: alpha.de.repo.voidlinux.org
xbps_repository_port: 443

telegraf:
  remotes:
    - host: "{{ influxdb_host }}"
  output:
    influxdb:
      url: "http://{{ influxdb_host }}:8086"
  agent:

metal_domain_root: '.m.voidlinux.org'
network_hostname: '{{ inventory_hostname | regex_replace(metal_domain_root, "") | regex_replace("\.", "-") }}'
network_fqdn: '{{ inventory_hostname }}'
network_boot_hosts:
  - addr: 148.251.199.117
    name: netauth.voidlinux.org
